apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pizzago-api-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nathan-Silva/pizzago-infra-gitops
    targetRevision: main
    path: apps/pizzago-api/overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: pizzago-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
