apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rendered.yaml

namespace: pizzago-prod

commonLabels:
  app.kubernetes.io/instance: pizzago-api-prod
